New cli documentation
Verisimilitude11/DNAnalyzer pull request #244
Opened 2022-10-23 22:42 UTC by plopez26DPU

Closes issue #218 

* [x] add CLI argument `build` documentation
* [x] add CLI understanding documentation
* [x] add accessing help menu
* [x] add running example 
* [x] take new screenshots
* [x] add all screenshots into documentation

2022-10-23 22:49 UTC, plopez26DPU commented
Not sure what needs to be refactored, but it is concise as is.

2022-10-24 00:45 UTC, Verisimilitude11 requested changes
This looks great @plopez26DPU. Could you please clear the merge conflicts? This PR is first in our backlog, so I'll merge once you clear them. Thanks!

2022-10-24 01:54 UTC, plopez26DPU commented
I think I fixed the issues @Verisimilitude11 , let me know if you have anymore issues :)

2022-10-24 03:03 UTC, Verisimilitude11 requested changes
It looks excellent, @plopez26DPU! I added a couple of comments, but everything else looks fine. I'll merge once you complete that.

2022-10-24 03:03 UTC, Verisimilitude11 commented on docs/samples/serine-dnalong.md
> +**IMPORTANT**
Label this with a title, for example, `OS-Specific Build Commands`

2022-10-24 03:03 UTC, Verisimilitude11 commented on docs/samples/serine-dnalong.md
> +The CLI is consisted of two parts.
The CLI consists of two parts.

2022-10-24 03:03 UTC, Verisimilitude11 commented on docs/samples/serine-dnalong.md
> +You will get the following response:
You should get the following response:

2022-10-24 03:03 UTC, Verisimilitude11 commented on docs/samples/serine-dnalong.md
> +You will get the following response:
You should get the following response:

2022-10-24 03:03 UTC, Verisimilitude11 commented on docs/samples/serine-dnalong.md
> +# CLI Arguments - Example
Rename the file to this

2022-10-25 00:11 UTC, plopez26DPU commented
Check it out and let me know :)

2022-10-25 02:26 UTC, Verisimilitude11 commented
It looks fantastic, @plopez26DPU! By the way, would you like to join our Discord server to communicate more efficiently?

2022-10-25 02:27 UTC, Verisimilitude11 approved these changes

2022-10-25 02:27 UTC, merged

2022-10-25 02:31 UTC, plopez26DPU commented
@Verisimilitude11 , sure ! That would be awesome . Do you have a invite link ?

2022-10-25 03:12 UTC, Verisimilitude11 commented
I posted a link in this discussion forum: https://github.com/Verisimilitude11/DNAnalyzer/discussions/256.

Congrats on completing Hacktoberfest!!! 🎉Will you still be interested in contributing after it ends? I greatly value your skill and expertise in DNAnalyzer, especially as we develop a front end and incorporate machine learning!

2022-10-25 03:25 UTC, plopez26DPU commented
@Verisimilitude11 , of course I would like to continue to contribute to the project. I look forward to it

2022-10-25 03:44 UTC, Verisimilitude11 commented
Excellent; thank you so much for your continued support!